Add RNA-SeQC at Quantification Section
danielecook/Awesome-Bioinformatics pull request #68
Opened 2020-11-07 06:01 UTC by dandyrilla

I've added additional quantification software.

2020-11-07 08:21 UTC, TGotwig requested changes

2020-11-07 08:21 UTC, TGotwig commented on README.md
> +- **[RNA-SeQC](https://software.broadinstitute.org/cancer/cga/rna-seqc)** - RNA-seq metrics for quality control and process optimization. [ [paper-2012](https://academic.oup.com/bioinformatics/articl
Hello dandyrilla 👋
```suggestion
 - **[RNA-SeQC](https://github.com/getzlab/rnaseqc)** - RNA-seq metrics for quality control and process optimization. [ [paper-2012](https://academic.oup.com/bioinformatics/article/28/11/1530/267467) | [web](https://software.broadinstitute.org/cancer/cga) ]
```

2020-11-09 00:35 UTC, dandyrilla commented
@TGotwig Thanks for suggesting!

2020-11-09 11:27 UTC, TGotwig commented
@dandyrilla Please also create `.markdownlint.json` with the following content 😊

```json
{
  "line-length": false
}
```

2020-11-10 09:51 UTC, dandyrilla commented
> @dandyrilla Please also create `.markdownlint.json` with the following content 😊
> 
> ```json
> {
>   "line-length": false
> }
> ```

Did I contain any line causing markdown syntax error?
I thought that the line causing error is not mine.
@TGotwig , Could you help me how to add `.markdownlint.json` to fix it up?

2020-11-10 09:56 UTC, TGotwig commented
@dandyrilla It's just a file which should be created inside the root folder of this project.

2020-11-11 00:43 UTC, closed without merging